name: NextJS Docker CI CD

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo 📦
              uses: actions/checkout@v4
            - name: Create .env.local File 📄
              run: |
                  echo "NEXT_PUBLIC_ENV=PROD" >> .env.local
                  echo "NEXT_PUBLIC_API_HOST=http://localhost:3001" >> .env.local
                  cat .env.local
            - name: Build Docker Image 🐳
              run: |
                  docker build -t i-www.chitubox.com-en .
            - name: Check Docker Images 🥽
              run: |
                  docker images
                  docker save i-www.chitubox.com-en -o i-www.chitubox.com-en.tar
                  chmod go+rw i-www.chitubox.com-en.tar
                  ls -l
            - name: Transfer Image tar File to Server 🚢
              uses: appleboy/scp-action@master
              with:
                  host: ${{ vars.HOST }}
                  username: ${{ vars.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ vars.PORT }}
                  source: i-www.chitubox.com-en.tar
                  target: /var/www/html/
            - name: Load the Docker Image and Run Container 🚀
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ vars.HOST }}
                  username: ${{ vars.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ vars.PORT }}
                  script: |
                      docker stop c-www.chitubox.com-en
                      docker rm c-www.chitubox.com-en
                      docker rmi i-www.chitubox.com-en
                      cd /var/www/html/
                      docker load -i i-www.chitubox.com-en.tar
                      rm i-www.chitubox.com-en.tar
                      docker run --name c-www.chitubox.com-en -p 3005:3000 -d i-www.chitubox.com-en
